const products = [
  {
    id: "1",
    name: "Box Storage Bed",
    price: 14000,
    image: "/assets/images/img1.jpg",
    desc:"Stanhope Engineered Wood King Size Box Storage Upholstered Bed In Finish(Product Dimensions : 99.0 cm x 210.0 cm x 237.0 cm)",
  },
  {
    id: "2",
    name: "Spine care health bed",
    price: 13000,
    image: "/assets/images/img2.jpg",
    desc:"Spine Support Orthopedic Multi Layered Double Coir Mattress(Product Dimensions : 198.0 cm x 122.0 cm)",

  },
  {
    id: "3",
    name: "Solid wood single bed",
    price: 8500,
    image: "/assets/images/img3.jpg",
    desc:"Nerja Solid Wood Single Non Storage Bed In Teak Finish(Product Dimensions : 79.0 cm x 204.0 cm x 98.0 cm)",
  },
  {
    id: "4",
    name: "Bosston single bed",
    price: 9000,
    image: "/assets/images/img4.jpg",
    desc:"Boston Solid Wood Size Bed In Teak Finish (Product Dimensions : 90.0 cm x 129.0 cm x 208.0 cm)",
  },
  {
    id: "5",
    name: "Royal wood office table",
    price: 12000,
    image: "/assets/images/img5.jpg",
    desc:"Royal Engineered Wood Office Table In Finish (Product Dimensions : 75.0 cm x 90.0 cm x 210.0 cm)",
  },
  {
    id: "6",
    name: "Glass finish table",
    price: 9500,
    image: "/assets/images/img6.jpg",
    desc:"Eddings Engineered Wood Study Table In Natural Oak and Glass Finish (Product Dimensions : 75.0 cm x 130.0 cm x 65.0 cm)",
  },

  {
    id: "7",
    name: "Oak finish table",
    price: 20000,
    image: "/assets/images/img7.jpg",
    desc:"Niccol Engineered Wood Study Table In Oak Finish (Product Dimensions : 78.0 cm x 168.0 cm x 55.0 cm)",
  },
  {
    id: "8",
    name: "Clint wood table",
    price: 11000,
    image: "/assets/images/img8.jpg",
    desc:"Clint Engineered Wood Study Table In Finish (Product Dimensions : 76.0 cm x 180.0 cm x 220.0 cm)",
  },
  {
    id: "9",
    name: "Lawswood dining table ",
    price: 11900,
    image: "/assets/images/img9.jpg",
    desc:"Lawson Solid Wood 6 Seater Dining Table With Set Of Chairs in Walnut Finish (Dimensions : 77.0 cm x 42.0 cm x 50.0 cm)",
  },
  {
    id: "10",
    name: "Soliwood dining table",
    price: 12300,
    image: "/assets/images/img10.jpg",
    desc:"Diner Solid Wood 6 Seater Dining Table With Set Of Chairsin Golden Oak Finish (Product Dimensions : 76.0 cm x 150.0 cm x 90.0 cm)",
  },
  {
    id: "11",
    name: "Floret dining table",
    price: 9999,
    image: "/assets/images/img11.jpg",
    desc:"Floret Solid Wood 4 Seater Dining Table With Set Of Chairs In Matte Finish (Product Dimensions : 90.0 cm x 75.0 cm x 120.0 cm)",
  },
  {
    id: "12",
    name: "Metal dining table",
    price: 10790,
    image: "/assets/images/img12.jpg",
    desc:"Celeste Metal 2 Seater Dining Table With Set Of Chairs In Glossy Finish (Product Dimensions : 76.0 cm x 61.0 cm x 61.0 cm)",
  },
  {
    id: "13",
    name: "Kosmo Wardrobe",
    price: 27890,
    image: "/assets/images/img13.jpg",
    desc:"Kosmo Engineered Wood 4 Door Wardrobe With Mirror In Matte Finish (Product Dimensions : 213.0 cm x 168.0 cm x 53.0 cm)",
  },
  {
    id: "14",
    name: "Luxuria matte Wardrobe",
    price: 23300,
    image: "/assets/images/img14.jpg",
    desc:"Luxuria Engineered Wood 2 Door Wardrobe With Mirror In Matte Finish (Product Dimensions : 183.0 cm x 80.0 cm x 46.0 cm)",
  },
  {
    id: "15",
    name: "Estansa wardrobe",
    price: 45600,
    image: "/assets/images/img15.jpg",
    desc:"Estana Engineered Wood 5 Door Wardrobe In Brown Finish (Product Dimensions : 200.0 cm x 56.0 cm x 200.0 cm)",
  },
  {
    id: "16",
    name: "Teak finish wardrobe",
    price: 12750,
    image: "/assets/images/img16.jpg",
    desc:"Ozone Engineered Wood 2 Door Wardrobe In Brown Finish (Product Dimensions : 180.0 cm x 46.0 cm x 74.0 cm)",
  },
];

export default products;
