const products = [
  {
    id: "1",
    name: "Box Storage Bed",
    price: 14000,
    image: "/assets/images/img1.jpg",
    desc:"Stanhope Engineered Wood King Size Box Storage Upholstered Bed In Finish(Product Dimensions : 99.0 cm x 210.0 cm x 237.0 cm)",
  },
  {
    id: "2",
    name: "Spine care health bed",
    price: 13000,
    image: "/assets/images/img2.jpg",
    desc:"Spine Support Orthopedic Multi Layered Double Coir Mattress(Product Dimensions : 198.0 cm x 122.0 cm)",

  },
  {
    id: "3",
    name: "Solid wood single bed",
    price: 8500,
    image: "/assets/images/img3.jpg",
    desc:"Nerja Solid Wood Single Non Storage Bed In Teak Finish(Product Dimensions : 79.0 cm x 204.0 cm x 98.0 cm)",
  },
  {
    id: "4",
    name: "Bosston single bed",
    price: 9000,
    image: "/assets/images/img4.jpg",
    desc:"Boston Solid Wood Size Bed In Teak Finish(Product Dimensions : 90.0 cm x 129.0 cm x 208.0 cm)",
  },
  {
    id: "5",
    name: "Royal wood office table",
    price: 12000,
    image: "/assets/images/img5.jpg",
    desc:"",
  },
  {
    id: "6",
    name: "Glass finish table",
    price: 9500,
    image: "/assets/images/img6.jpg",
    desc:"",
  },

  {
    id: "7",
    name: "Oak finish table",
    price: 20000,
    image: "/assets/images/img7.jpg",
    desc:"",
  },
  {
    id: "8",
    name: "Clint wood table",
    price: 11000,
    image: "/assets/images/img8.jpg",
    desc:"",
  },
  {
    id: "9",
    name: "Lawswood dining table ",
    price: 11900,
    image: "/assets/images/img9.jpg",
    desc:"",
  },
  {
    id: "10",
    name: "Soliwood dining table",
    price: 12300,
    image: "/assets/images/img10.jpg",
    desc:"",
  },
  {
    id: "11",
    name: "Floret dining table",
    price: 9999,
    image: "/assets/images/img11.jpg",
    desc:"",
  },
  {
    id: "12",
    name: "Metal dining table",
    price: 10790,
    image: "/assets/images/img12.jpg",
    desc:"",
  },
  {
    id: "13",
    name: "Kosmo Wardrobe",
    price: 27890,
    image: "/assets/images/img13.jpg",
    desc:"",
  },
  {
    id: "14",
    name: "Luxuria matte Wardrobe",
    price: 23300,
    image: "/assets/images/img14.jpg",
    desc:"",
  },
  {
    id: "15",
    name: "Estansa wardrobe",
    price: 45600,
    image: "/assets/images/img15.jpg",
    desc:"",
  },
  {
    id: "16",
    name: "Teak finish wardrobe",
    price: 12750,
    image: "/assets/images/img16.jpg",
    desc:"",
  },
];

export default products;
